version: '3.9'

services:
  laminas:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
  laminas-db:
    image: mariadb:10.6.5
    container_name: laminas-db
    ports:
      - "3308:3306"
    environment:
      MARIADB_USER: sander2
      MARIADB_PASSWORD: gravity35
      MARIADB_DATABASE: sander33
      MARIADB_ROOT_PASSWORD: icanwrite
    volumes:
      - ./docker/sql/laminas-db:/docker-entrypoint-initdb.d/
      - laminas-db:/var/lib/mysql
volumes:
  laminas-db: ~