<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Cyborg - Awesome HTML5 Template')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet('https://unpkg.com/swiper@7/swiper-bundle.min.css')
        ->prependStylesheet($this->basePath('assets/css/animate.css'))
        ->prependStylesheet($this->basePath('assets/css/owl.css'))
        ->prependStylesheet($this->basePath('assets/css/templatemo-cyborg-gaming.css'))
        ->prependStylesheet($this->basePath('assets/css/fontawesome.css'))
        ->prependStylesheet($this->basePath('vendor/bootstrap/css/bootstrap.min.css'))
    ?>

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- Scripts -->
    <?= $this->headScript() ?>


</head>
<body>

<!-- ***** Preloader Start ***** -->
<div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
        <span class="dot"></span>
        <div class="dots">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
</div>
<!-- ***** Preloader End ***** -->

<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="index.html" class="logo">
                        <img src="assets/images/logo.png" alt="">
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Search End ***** -->
                    <div class="search-input">
                        <form id="search" action="#">
                            <input type="text" placeholder="Type Something" id='searchText' name="searchKeyword"
                                   onkeypress="handle"/>
                            <i class="fa fa-search"></i>
                        </form>
                    </div>
                    <!-- ***** Search End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <!-- Navigation -->
                        <?= $this->mainMenu()->render(); ?>
                    </ul>

                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ***** Header Area End ***** -->

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-content">
                <?= $this->content ?>
            </div>
        </div>
    </div>
</div>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright © 2036 <a href="#">Cyborg Gaming</a> Company. All rights reserved.

                    <br>Design: <a href="https://templatemo.com" target="_blank"
                                   title="free CSS templates">TemplateMo</a> Distributed By <a
                            href="https://themewagon.com" target="_blank">ThemeWagon</a></p>
            </div>
        </div>
    </div>
</footer>
<?=
$this->inlineScript()
    ->prependFile($this->basePath('assets/js/custom.js'))
    ->prependFile($this->basePath('assets/js/popup.js'))
    ->prependFile($this->basePath('assets/js/tabs.js'))
    ->prependFile($this->basePath('assets/js/owl-carousel.js'))
    ->prependFile($this->basePath('assets/js/isotope.min.js'))
    ->prependFile($this->basePath('vendor/bootstrap/js/bootstrap.min.js'))
    ->prependFile($this->basePath('vendor/jquery/jquery.min.js'))
?>
</body>
</html>
