<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Verzeilberg.nl')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap')
        ->prependStylesheet('https://unpkg.com/swiper@7/swiper-bundle.min.css')
        ->prependStylesheet($this->basePath('assets/css/animate.css'))
        ->prependStylesheet($this->basePath('assets/css/owl.css'))
        ->prependStylesheet($this->basePath('assets/css/templatemo-cyborg-gaming.css'))
        ->prependStylesheet($this->basePath('assets/css/fontawesome.css'))
        ->prependStylesheet($this->basePath('vendor/bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css')
    ?>

    <!-- Scripts -->
    <?=
    $this->inlineScript()
        ->prependFile($this->basePath('assets/js/custom.js'))
        ->prependFile($this->basePath('assets/js/popup.js'))
        ->prependFile($this->basePath('assets/js/tabs.js'))
        ->prependFile('https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js')
        ->prependFile($this->basePath('assets/js/owl-carousel.js'))
        ->prependFile($this->basePath('vendor/bootstrap/js/bootstrap.min.js'))
        ->prependFile($this->basePath('assets/js/isotope.min.js'))
        ->prependFile($this->basePath('vendor/jquery/jquery.min.js'))
    ?>
    <script>
        $( document ).ready(function() {
            Fancybox.bind("[data-fancybox]", {
                // Your custom options
            });
        });
    </script>

    <!-- More scripts -->
    <?= $this->headScript() ?>


</head>
<body>

<!-- ***** Preloader Start ***** -->
<div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
        <span class="dot"></span>
        <div class="dots">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
</div>
<!-- ***** Preloader End ***** -->



<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="/" class="logo">
                        <h1>Verzeilberg</h1>
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Search End ***** -->
                    <!--
                    <div class="search-input">
                        <form id="search" action="#">
                            <input type="text" placeholder="Type Something" id='searchText' name="searchKeyword"
                                   onkeypress="handle"/>
                            <i class="fa fa-search"></i>
                        </form>
                    </div> -->
                    <!-- ***** Search End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <!-- Navigation -->
                        <?= $this->mainMenu()->render(); ?>
                    </ul>

                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ***** Header Area End ***** -->

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-content">
                <?= $this->content ?>
            </div>
        </div>
    </div>
</div>
<footer>
    <div class="container">
        <div class="row mt-4">
            <div class="col-lg-10 mx-auto text-center">
                <ul class="social-icons">
                    <li>
                        <a href="mailto:info@verzeilberg.nl">
                            <i class="fas fa-envelope"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.twitter.com/verzeilberg" target="new">
                            <i class="fab fa-twitter fa-fw"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://nl.pinterest.com/sannder4893/" target="new">
                            <i class="fab fa-pinterest fa-fw"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.youtube.com/channel/UC86Xp0QHgiBSZRJedRlxCtQ" target="new">
                            <i class="fab fa-youtube fa-fw"></i>
                        </a>
                    </li>

                    <li>
                        <a href="https://www.linkedin.com/in/sanderverzeilberg/" target="new">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.strava.com/athletes/verzeilberg" class="text-danger" target="new">
                            <i class="fab fa-strava"></i>
                        </a>
                    </li>
                </ul>
                <hr class="small">
                <p class="copyright">&copy; 2016 - <?php echo date('Y') ?></p>
            </div>
        </div>
    </div>
</footer>

</body>
</html>
