<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->headLink([
            'rel' => 'stylesheet',
            'href' => $this->basePath('css/bootstrap.min.css'),
            'type' => 'text/css'
        ])
        ->headLink([
            'rel' => 'stylesheet',
            'href' => $this->basePath('css/font-awesome.min.css'),
            'type' => 'text/css'
        ])
        ->headLink([
            'rel' => 'stylesheet',
            'href' => $this->basePath('css/elegant-icons.css'),
            'type' => 'text/css'
        ])
        ->headLink([
            'rel' => 'stylesheet',
            'href' => $this->basePath('css/plyr.css'),
            'type' => 'text/css'
        ])
        ->headLink([
            'rel' => 'stylesheet',
            'href' => $this->basePath('css/nice-select.css'),
            'type' => 'text/css'
        ])
        ->headLink([
            'rel' => 'stylesheet',
            'href' => $this->basePath('css/owl.carousel.min.css'),
            'type' => 'text/css'
        ])
        ->headLink([
            'rel' => 'stylesheet',
            'href' => $this->basePath('css/slicknav.min.css'),
            'type' => 'text/css'
        ])
        ->headLink([
            'rel' => 'stylesheet',
            'href' => $this->basePath('css/style.css'),
            'type' => 'text/css'
        ])
        ->headLink([
            'rel' => 'stylesheet',
            'href' => 'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap'
        ])
        ->headLink([
            'rel' => 'stylesheet',
            'href' => 'https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"',
        ]);
    //->prependStylesheet($this->basePath('css/colors/red.css'))
    ?>
    <!-- Scripts -->
    <?= $this->HeadScript()->appendFile('https://kit.fontawesome.com/6d7a12ed89.js', 'text/javascript', [
        'crossorigin' => 'anonymous'
    ]); ?>
    <?= $this->HeadScript()->appendFile('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js', 'text/javascript',
        [
            'integrity' => 'sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p',
            'crossorigin' => 'anonymous'
        ]); ?>

</head>
<body>
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="./index.html">
                        <img src="img/logo.png" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="header__nav">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li class="active"><a href="./index.html">Homepage</a></li>
                            <li><a href="./categories.html">Categories <span class="arrow_carrot-down"></span></a>
                                <ul class="dropdown">
                                    <li><a href="./categories.html">Categories</a></li>
                                    <li><a href="./anime-details.html">Anime Details</a></li>
                                    <li><a href="./anime-watching.html">Anime Watching</a></li>
                                    <li><a href="./blog-details.html">Blog Details</a></li>
                                    <li><a href="./signup.html">Sign Up</a></li>
                                    <li><a href="./login.html">Login</a></li>
                                </ul>
                            </li>
                            <li><a href="./blog.html">Our Blog</a></li>
                            <li><a href="#">Contacts</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="header__right">
                    <a href="#" class="search-switch"><span class="icon_search"></span></a>
                    <a href="./login.html"><span class="icon_profile"></span></a>
                </div>
            </div>
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
</header>
<!-- Header End -->
<?= $this->content ?>
<!-- Footer Section Begin -->
<footer class="footer">
    <div class="page-up">
        <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="footer__nav">
                    <ul>
                        <li class="active"><a href="./index.html">Homepage</a></li>
                        <li><a href="./categories.html">Categories</a></li>
                        <li><a href="./blog.html">Our Blog</a></li>
                        <li><a href="#">Contacts</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->
<!-- Js Plugins -->
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/main.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/player.js'))
    ->prependFile($this->basePath('js/jquery.nice-select.min.js'))
    ->prependFile($this->basePath('js/mixitup.min.js'))
    ->prependFile($this->basePath('js/jquery.slicknav.js'))
    ->prependFile($this->basePath('js/owl.carousel.min.js'))
    ->prependFile($this->basePath('js/jquery-3.3.1.min.js'));
?>
</body>
</html>
