<?php if ($this->pageCount > 1): ?>
    <nav aria-label="Page navigation">
        <ul class="pagination">

            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="page-item">
                    <a class="page-link bg-dark text-white" href="<?= $this->url($this->route, ['action' => $this->action], ['query'=>['page'=>$this->previous]]); ?>" aria-label="Previous">
                        <i class="fas fa-angle-double-left"></i>
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li class="page-item bg-dark">
                        <a class="page-link bg-dark text-white" href="<?= $this->url($this->route, ['action' => $this->action], ['query'=>['page'=>$page]]); ?>"><?= $this->escapeHtml($page); ?></a>
                    </li>
                <?php else: ?>
                    <li class="page-item bg-dark">
                        <span class="page-link bg-secondary text-white" aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li class="page-item">
                    <a class="page-link bg-dark text-white" href="<?php echo $this->url($this->route, ['action' => $this->action], ['query'=>['page'=>$this->next]]); ?>" aria-label="Next">
                        <i class="fas fa-angle-double-right"></i>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
<?php endif; ?>