<!-- ***** Banner Start ***** -->
<div class="main-banner">
    <div class="row">
        <div class="col-lg-7">
            <div class="header-text">

            </div>
        </div>
    </div>
</div>
<!-- ***** Banner End ***** -->

<!-- ***** Blog Start ***** -->
<div class="most-popular">
    <div class="row">
        <div class="col-lg-12">
            <div class="heading-section">
                <h4><em>Blogs</em> Right Now</h4>
            </div>
            <div class="row blogItems">
                <?php foreach ($blogs as $blog) { ?>
                    <?php
                    $images = $blog->getBlogImages();
                    foreach ($images as $image) {
                        foreach ($image->getImageTypes('800x600') as $imageType) {
                            $blogImage = '<img src="/' . $imageType->getFolder() . $imageType->getFileName() . '" alt="' . $image->getAlt() . '">';
                            break;
                        }
                        break;
                    }
                    ?>
                    <div class="col-lg-4 col-sm-6">
                        <div class="item">
                            <?= $blogImage ?>
                            <h4><?= $blog->getTitle(); ?>
                                <br><span><?= !empty($blog->getCategories()->first()) ? $blog->getCategories()->first()->getName() : ''; ?></span>
                            </h4>
                            <ul>
                                <li><i class="fa fa-star"></i> 4.8</li>
                                <li><i class="fa fa-download"></i> 2.3M</li>
                            </ul>
                        </div>
                    </div>
                <?php } ?>
                <div class="col-lg-12">
                    <div class="main-button">
                        <a href="<?php echo $this->url('blog', ['action' => 'index']); ?>"
                           class="btn btn-dark"><?php echo $this->translate('Discover More Blogs'); ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Blog End ***** -->

<!-- ***** Running stats Start ***** -->
<div class="running-stats most-popular">
    <div class="row">
        <div class="col-lg-12">
            <div class="heading-section">
                <h4><em>Running</em> Stats</h4>
            </div>
            <div class="row">
                <div class="col-lg-2 col-sm-12 mb-3">
                    <div class="card bg-success">
                        <div class="card-header text-center">
                            <i class="fa fa-running"></i>
                            <h5 class="card-title text-center mt-2">Totaal activiteiten</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center"><?= $totalRunActivities ?></h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-12">
                    <div class="card bg-warning">
                        <div class="card-header text-center">
                            <i class="fas fa-tachometer-alt"></i>
                            <h5 class="card-title text-center mt-2">Gemiddelde tempo</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                <?= $this->stravaViewHelper()->getAverageSpeed($averageSpeed) ?>
                            </h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-12">
                    <div class="card bg-secondary">
                        <div class="card-header text-center">
                            <i class="fas fa-road"></i>
                            <h5 class="card-title text-center mt-2">Totaal km's</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                <?= $this->stravaViewHelper()->getDistance($totalRunDistance) ?> km
                            </h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-12">
                    <div class="card bg-dark">
                        <div class="card-header text-center">
                            <i class="fas fa-stopwatch"></i>
                            <h5 class="card-title text-center mt-2">Totaal tijd</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                <?= $this->stravaViewHelper()->getTotalMovingTime($totalRunTime); ?>
                            </h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-12">
                    <div class="card bg-info">
                        <div class="card-header text-center">
                            <i class="fas fa-mountain"></i>
                            <h5 class="card-title text-center mt-2">Gemiddelde hoogteverschil</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                <?= $this->stravaViewHelper()->getTotalElevationGain($averageElevation); ?>
                            </h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-12">
                    <div class="card bg-danger">
                        <div class="card-header text-center">
                            <i class="fas fa-heartbeat"></i>
                            <h5 class="card-title text-center mt-2">Gemiddelde hartslag</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                <?= $this->stravaViewHelper()->getTotalElevationGain($averageHeartbeat); ?>
                            </h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="main-button">
                        <a href="<?php echo $this->url('runningStats'); ?>"
                           class="btn btn-dark"><?php echo $this->translate('Get statisfied'); ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Running stats End ***** -->
<!-- ***** Events Start ***** -->
<?php if (is_object($upcommingEvent)) { ?>
    <?php
    $imageURL = '';
    $image = $upcommingEvent->getEventImage();
    if (is_object($image)) {
        foreach ($image->getImageTypes('original') as $imageType) {
            $imageURL = $imageType->getFolder() . $imageType->getFileName();
            break;
        }
    }
    ?>
    <div class="most-popular"
         style="background: url(<?php echo $imageURL; ?>) no-repeat center center scroll;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-section">
                    <h4><em>Upcomming</em> event</h4>
                </div>

                <div class="col-lg-12 col-sm-12 mb-2">
                    <div class="text-vertical-center">
                        <h3 class="eventTitle text-center mb-2"><?php echo $upcommingEvent->getTitle(); ?></h3>
                        <div class="clock"></div>
                        <input type="hidden" name="eventDate"
                               value="<?php echo(is_object($upcommingEvent->getEventStartDate()) ? $upcommingEvent->getEventStartDate()->format('j M Y G:i:s') : ''); ?>"/>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="main-button">
                        <a href="<?php echo $this->url('events'); ?>"
                           class="btn btn-dark"><?php echo $this->translate('More events'); ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
<!-- ***** Events End ***** -->
<!-- ***** Start Stream Start ***** -->
<div class="start-stream">
    <div class="col-lg-12">
        <div class="heading-section">
            <h4><em>Tweets</em> What's going on?</h4>
        </div>
        <div class="row">
            <?php foreach ($tweets as $tweet) { ?>
                <div class="col-lg-3">
                    <div class="item tweet-item">
                        <h4><?= $tweet['tweet_date']; ?></h4>
                        <p><?= $tweet['tweet_text']; ?></p>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<!-- ***** Start Stream End ***** -->

<!-- ***** Gaming Library Start ***** -->
<div class="gaming-library">
    <div class="col-lg-12">
        <div class="heading-section">
            <h4><em>Your Gaming</em> Library</h4>
        </div>
        <?php foreach ($steamGames as $index => $game) { ?>
            <div class="item <?= $index === 2?'last_item':'' ?>">
                <h4><?= $game['name'] ?></h4><span><?= $game['genres'] ?></span>
                <ul>
                    <li><img src="<?= $game['image'] ?>" alt="<?= $game['name'] ?>"></li>
                    <li><h4>Last Played</h4><span><?= $game['last_played'] ?></span></li>
                    <li><h4>Hours Played</h4><span><?= $game['play_time'] ?></span></li>
                    <li>
                        <h4>Achievements</h4>
                        <span>
                            <?= $game['achievements']['totalAchievements'] ?>
                            /
                            <?= $game['achievements']['totalFinishedAchievements'] ?>
                        </span>
                    </li>
                </ul>
            </div>
        <?php } ?>
    </div>
    <div class="col-lg-12">
        <div class="main-button">
            <a href="profile.html">View Your Library</a>
        </div>
    </div>
</div>
<!-- ***** Gaming Library End ***** -->